-- Generated by the database client.
CREATE TABLE bibliotecario(
    id SERIAL NOT NULL,
    nome varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE livro(
    id SERIAL NOT NULL,
    bibliotecario integer NOT NULL,
    titulo varchar(255) NOT NULL,
    autor varchar(255) NOT NULL,
    genero varchar(255) NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'Disponível'::character varying,
    created_date date NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT livro_bibliotecario_fkey FOREIGN key(bibliotecario) REFERENCES bibliotecario(id)
);
